server {
    listen 8080;
    host localhost;
    server_name YoupiBanane;
    index index.html;
    location / {
        root YoupiBanane;
        index index.html;
        allow_methods GET;
        autoindex off;
    }
    location /youpi.bla {
        root YoupiBanane;
        allow_methods POST;
        cgi .bla /home/cjauregu/Downloads/webserv_lylah/cgi_tester;
    }
    location /post_body {
        root YoupiBanane;
        allow_methods POST;
        upload_store YoupiBanane/post_body;
        client_max_body_size 100;
    }
    location /directory {
        root YoupiBanane;
        allow_methods GET POST;
        index youpi.bad_extension;
        upload_store YoupiBanane/directory;
        autoindex off;
    }
}
