server {
	server_name main;
	listen 8080;
	host localhost;
	root /path/of/your/webserv/websites/main;
	index index.html;
	client_max_body_size 10;
	error_page 404.html;
	location / {
		methods		POST GET
		root		idk/
		index		idk/
		autodindex	on
	}
	location /upload {
		methods		POST
		root		idk/
		autodindex	on
	}
	location /delete {
		methods	DELETE
		root	where/posts/are/uploaded
	}
	location /cgi {
		methods	POST GET
		root	idk/
		#cgi
	}
	location /old {
		301 #perm redirect
		302 #temp redirect
	}
}
